# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('num_of_elements', models.IntegerField(default=0)),
                ('num_of_conflicts', models.IntegerField(default=0)),
                ('has_reward', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('has_reward', 'num_of_elements'),
            },
        ),
        migrations.CreateModel(
            name='TaskConflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=200)),
                ('info1', models.CharField(max_length=200)),
                ('info2', models.CharField(max_length=200)),
                ('info3', models.CharField(max_length=200)),
                ('conflict_name', models.CharField(max_length=200)),
                ('conflict_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('is_fixed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('info1', models.CharField(max_length=200)),
                ('info2', models.CharField(max_length=200)),
                ('info3', models.CharField(max_length=200)),
                ('element_name', models.CharField(max_length=200)),
                ('element_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('tasks', models.ManyToManyField(related_name='task_element', to='base.Task')),
            ],
        ),
        migrations.AddField(
            model_name='taskconflict',
            name='element',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.TaskElement'),
        ),
        migrations.AddField(
            model_name='taskconflict',
            name='tasks',
            field=models.ManyToManyField(related_name='task_conflict', to='base.Task'),
        ),
    ]
