# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconflict',
            name='building_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskelement',
            name='building_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
