# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170227_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=100)),
                ('experienced', models.BooleanField(default=False)),
                ('nationality', models.CharField(max_length=200)),
                ('know_microtasking', models.BooleanField(default=False)),
            ],
        ),
    ]
