# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170314_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='description_geom',
        ),
        migrations.AddField(
            model_name='task',
            name='description_meta',
            field=models.TextField(default='In this task you see building layers on the map. You are suppose to chose the most accurate geometry layer for the buildings marked on the map. Do this for all the buildings. When you have clicked on the correct layers, click next. In the next task the table show the metadata in each layer. Choose which layer that has the most informative metadata about each building. Do this for each building.'),
            preserve_default=False,
        ),
    ]
