# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 14:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170314_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='buildings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1, 2, 3, 4, 5, 6], size=None),
            preserve_default=False,
        ),
    ]
