# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 08:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170207_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=200)),
                ('task_element', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('is_imported', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskobject',
            name='task',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('has_reward', 'num_of_elements')},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='num_of_obj',
            new_name='num_of_elements',
        ),
        migrations.RenameField(
            model_name='taskconflict',
            old_name='task',
            new_name='tasks',
        ),
        migrations.DeleteModel(
            name='TaskObject',
        ),
        migrations.AddField(
            model_name='taskelement',
            name='tasks',
            field=models.ManyToManyField(related_name='task_element', to='base.Task'),
        ),
    ]
