# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20170208_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskconflict',
            old_name='task_conflict',
            new_name='conflict_geom',
        ),
        migrations.RenameField(
            model_name='taskelement',
            old_name='task_element',
            new_name='element_geom',
        ),
    ]
