# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20170224_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconflict',
            name='info1',
            field=models.CharField(default='no info', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskconflict',
            name='info2',
            field=models.CharField(default='no info', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskconflict',
            name='info3',
            field=models.CharField(default='no info', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskelement',
            name='info1',
            field=models.CharField(default='no info', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskelement',
            name='info2',
            field=models.CharField(default='no info', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskelement',
            name='info3',
            field=models.CharField(default='no info', max_length=200),
            preserve_default=False,
        ),
    ]
